name: CI/CD

on:
  push:
    tags:
      - v*


jobs:
  flutter_test:
    name: "Run Flutter analyze and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
        
        name: "Setup flutter SDK"
      - uses: subosito/flutter-action@v1
        
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
