name: Flutter Build Release APK

on:
  push:
    branches:
      - main # Ou qualquer outra branch de sua escolha
  pull_request:
    branches:
      - main # Ou qualquer outra branch de sua escolha

jobs:
  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Java (Versão recomendada para Flutter)
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Passo 3: Configurar o Flutter SDK
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      # Passo 4: Instalar dependências
      - name: Install dependencies
        run: flutter pub get

      # Passo 5: Rodar o comando flutter build para gerar o APK de release
      - name: Build APK (Release)
        run: flutter build apk --release

      # Passo 6: Fazer o upload do APK gerado (opcional)
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
